### ISSUE TITLE
Chapter 7 typos on page 163

### ISSUE THREAD

**Issue by johnarumemi** [PacktPublishing/Asynchronous-Programming-in-Rust#21]
The Errata in github is incorrect here

> Page 163 (Paragraph 4, line 2): The next coroutine/wait function is read_requests should be The next coroutine/wait function is requests

it is `request` singular, since that's the function name.

The same error to the `read_request` -> `request` function name was made in paragraph 2. "async_main stores a set of coroutines created by `read_requests` in a ..." should be "async_main stores a set of coroutines created by `request` in a ..."

**Comment by cfsamson** [comment]
Hi and sorry for the delay as I've been away for a few weeks. You're right. It's correct in my notes but I don't officially add the errata so that plural must have come as a mistake. Thanks for pointing it out. Yes, the same mistake is also in the second paragraph so I've reported it all to Packt so they can correct the existing one and add the omitted one like this:

Page 163:
Paragraph 2 should be “coroutines created by `request` in a `Vec<T: Future>`…”
Paragraph 4 should be “The next `coroutine/wait` function is `request` …
